//
//  MainPresenter.swift
//  Calculator+programmatic
//
//  Created by Rdm on 09/02/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentResults(response: Main.PerformOperation.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?

    func presentResults(response: Main.PerformOperation.Response) {
        let viewModel = Main.PerformOperation.ViewModel(text: response.text)
        viewController?.displayResults(viewModel: viewModel)
    }

}
